### Get all movies
GET http://localhost:8081/api/movies

### Get Matrix movie
GET http://localhost:8081/api/movies/74d7ec09-fb1c-4a04-8e49-ceb0d242fba6

### Get movie that doesn't exist
GET http://localhost:8081/api/movies/11111111-2222-3333-4444-123123123123

### Create new movie (wrong)
PUT http://localhost:8081/api/movies/5141234-3f8e-409c-a51f-b99e29c1406c
Content-Type: application/json

{
  "title": "Nowy Film",
  "director": "Test",
  "genreId": "91124165-92b8-46a1-8097-84d1c021641d",
  "releaseYear": 2018
}

### Delete movie - Incepcja
DELETE http://localhost:8081/api/movies/b4c2d75b-5e37-4b8b-9075-ddd1ce3b3198

### Update movie - Fight Club
PATCH http://localhost:8081/api/movies/74d7ec09-fb1c-4a04-8e49-ceb0d242fba6
Content-Type: application/json

{
  "title": "Fight Club - zmieniony tytuł",
  "director": "David Fincher"
}

### Get movies in genre - Drama
GET http://localhost:8081/api/genres/91124165-92b8-46a1-8097-84d1c021641d/movies

### Get movies in genre - genre doesn't exist
GET http://localhost:8081/api/genres/91124165-1111-1111-1111-84d1c021641d/movies